Military/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mod.urls"))
]

mod/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path('form', views.submit_application, name='submit_application'),
    path('view-applications/', views.view_applications, name='view_applications'),
]

mod/models.py
from django.db import models

# Create your models here.
class EnlistmentApplication(models.Model):
    EDUCATION_CHOICES = [
        ('high_school', 'High School Diploma'),
        ('associate', 'Associate Degree'),
        ('bachelor', 'Bachelor\'s Degree'),
        ('master', 'Master\'s Degree'),
        ('doctorate', 'Doctorate'),
    ]

    fullname = models.CharField(max_length=255)
    dob = models.DateField(verbose_name='Date of Birth')
    ssn = models.CharField(max_length=11, verbose_name='Social Security Number')
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    education = models.CharField(max_length=20, choices=EDUCATION_CHOICES)
    reasons = models.TextField(verbose_name='Reasons for Enlisting')
    history = models.TextField(verbose_name='Prior Military Service', blank=True, null=True)

    def __str__(self):
        return f"{self.fullname} - {self.ssn}"

mod/views.py
from django.shortcuts import render, redirect
from .models import EnlistmentApplication

# Create your views here
def home(request):
    return render(request, "web/index.html")

def submit_application(request):
    if request.method == 'POST':
        application = EnlistmentApplication(
            fullname=request.POST['fullname'],
            dob=request.POST['dob'],
            ssn=request.POST['ssn'],
            email=request.POST['email'],
            phone=request.POST['phone'],
            education=request.POST['education'],
            reasons=request.POST['reasons'],
            history=request.POST.get('history', '')  # Optional field
        )
        application.save()
        return render(request, 'view_applications.html', {'application': application})
    return render(request, 'submit_form.html')

def view_applications(request):
    applications = EnlistmentApplication.objects.all()
    return render(request, 'view_applications.html', {'applications': applications})

mod/templates/submit_form.html
{% load static %}

<!DOCTYPE html><html lang="en-US"><head>

<meta charset="utf-8">
<!-- 
	This website is powered by TYPO3 - inspiring people to share!
	TYPO3 is a free open source Content Management Framework initially created by Kasper Skaarhoj and licensed under GNU/GPL.
	TYPO3 is copyright 1998-2024 of Kasper Skaarhoj. Extensions are copyright of their respective owners.
	Information and contribution at https://typo3.org/
-->


<link rel="shortcut icon" href="typo3conf/ext/risa_base/Resources/Public/Images/Coat.png" type="image/png">
<title>MOD: Home</title>
<meta name="generator" content="TYPO3 CMS">
<meta name="twitter:card" content="summary">

<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/bootstrap.min_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/index_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/animate_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/sweetalert_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Fonts/style_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/ministry_ui_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3temp/assets/css/a2b50b40b2_1685369889.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/ns_twitter/Resources/Public/Css/style_1712913723.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/ns_twitter/Resources/Public/Css/font-awesome/css/font-awesome.min_1712913723.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/wacon_cookie_management/Resources/Public/Css/waconcookiemanagement_1712913727.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/material_icon_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/all_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/owl.carousel.min_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/owl.theme.default.min_1712913725.css' %}" media="all">



<script src="{% static 'typo3conf/ext/wacon_cookie_management/Resources/Public/JavaScript/jquery.min_1712913727.js' %}"></script>
<script src="{% static 'typo3conf/ext/risa_gov/Resources/Public/Javascript/smoothscroll_1712913725.js' %}"></script>


<meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, shrink-to-fit=no">    <script>
        (function (w, d, s, l, i) {
        w[l] = w[l] || []; w[l].push({
        'gtm.start':
            new Date().getTime(), event: 'gtm.js'
        }); var f = d.getElementsByTagName(s)[0],
        j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
            'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-NLR2CLH');
    </script>
<link rel="canonical" href="https://www.mod.gov.rw/">

<!-- This site is optimized with the Yoast SEO for TYPO3 plugin - https://yoast.com/typo3-extensions-seo/ -->
<script type="application/ld+json">[{"@context":"https://www.schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"item":{"@id":"https://www.mod.gov.rw/1","name":"MOD"}},{"@type":"ListItem","position":2,"item":{"@id":"https://www.mod.gov.rw/","name":"Home"}}]}]</script>

<style>
    input, textarea, select {
        border: 1px solid rgb(78, 78, 78) !important;
        border-radius: 4px;
        padding: 3px 5px;
        margin-bottom: 10px;
    }
</style>

</head>
<body>

<noscript>
  <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NLR2CLH" height="0" width="0"
    style="display:none;visibility:hidden">
  </iframe>
</noscript>

        <nav class="navbar sticky-top navbar-expand-lg navbar-light ministry_navbar" id="theNav">

<div class="container-fluid ministry_container">
  <a href="/" title="MOD" class="navbar-brand">
    <img src="{% static 'images/logo.png' %}" alt="Image" height="48">
</a>
<a href="/" title="MOD" class="navbar-brand logotext">
	<p class="txt_subtitle fnt_black  mabo0">MOD</p>
</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span id="navbar-hamburger" class="navbar-toggler-icon"></span>
    <span id="navbar-close" class="hidden"><i class="material-icons txt_content">close</i></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
      
        
            <li class="nav-item">
              <a class="nav-link main_option active" href="/" title="Home">
                Home
              </a>
            </li>
          
      
        
            <li class="nav-item">
              <a class="nav-link main_option " href="#" title="The Ministry">
                The Ministry
              </a>
            </li>
          
      
        
            <li class="nav-item">
              <a class="nav-link main_option " href="#" title="RDF">
                RDF
              </a>
            </li>
          
      
        
            <li class="nav-item">
              <a class="nav-link main_option " href="#" title="Activities">
                Activities
              </a>
            </li>
          
      
        
            <li class="nav-item">
              <a class="nav-link main_option " href="#" title="Updates">
                Updates
              </a>
            </li>
          
      
        
            <li class="nav-item">
              <a class="nav-link main_option " href="#" title="Publications">
                Publications
              </a>
            </li>


            <li class="nav-item">
              <a class="nav-link main_option " href="/form" title="Publications">
                Form
              </a>
            </li>
          
      
    </ul>

    
  </div>
</div>
</nav>


  <!-- SECTION LANDING STARTS -->
  <div class="container-fluid d-flex" id="section_landing">

    <div class="container align-self-center pad0">
        <h2 style="margin: 40px 0; text-transform: uppercase;">Enlistment Application Form</h2>
        <form action="{% url 'submit_application' %}" method="post">
            {% csrf_token %}
            <label for="fullname">Full Name:</label>
            <input type="text" id="fullname" name="fullname" required><br>
    
            <label for="dob">Date of Birth:</label>
            <input type="date" id="dob" name="dob" required><br>
    
            <label for="ssn">Social Security Number:</label>
            <input type="text" id="ssn" name="ssn" required><br>
    
            <label for="email">Email Address:</label>
            <input type="email" id="email" name="email" required><br>
    
            <label for="phone">Phone Number:</label>
            <input type="tel" id="phone" name="phone" required><br>
    
            <label for="education">Highest Level of Education Completed:</label>
            <select id="education" name="education">
                <option value="high_school">High School Diploma</option>
                <option value="associate">Associate Degree</option>
                <option value="bachelor">Bachelor's Degree</option>
                <option value="master">Master's Degree</option>
                <option value="doctorate">Doctorate</option>
            </select><br>
    
            <label for="reasons">Why do you want to enlist?</label><br>
            <textarea id="reasons" name="reasons" style="width: 300px; height: 100px;" required></textarea><br>
    
            <label for="history">Do you have any prior military service?</label>
            <input type="text" id="history" name="history"><br>
    
            <button type="submit" style="background-color: #078ECE; padding: 6px 12px; border: 1px solid rgb(155, 155, 155); border-radius: 5px; cursor: pointer;">Submit Application</button>
        </form>
    </div>
    </div>
<button onclick="topFunction()" id="backToTop" title="Go to top">↑<br><span class="txt_info txt_grey">Back top</span></button>

<!--SECTION FOOTER ENDS-->
<script src="{% static 'www.recaptcha.net/recaptcha/api_hl%3D.js' %}"></script>
<script src="{% static 'typo3conf/ext/risa_ministry/Resources/Public/JavaScript/jquery-3.6.0_1712913725.js' %}"></script>
<script src="{% static 'cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js' %}"></script>
<script src="{% static 'typo3conf/ext/risa_ministry/Resources/Public/JavaScript/popper.min_1712913725.js' %}"></script>
<script src="{% static 'typo3conf/ext/risa_ministry/Resources/Public/JavaScript/bootstrap.min_1712913725.js' %}"></script>
<script src="{% static 'typo3conf/ext/risa_ministry/Resources/Public/JavaScript/sweetalert.min_1712913725.js' %}"></script>
<script src="{% static 'typo3conf/ext/risa_ministry/Resources/Public/JavaScript/owl.carousel.min_1712913725.js' %}"></script>
<script src="{% static 'typo3conf/ext/risa_ministry/Resources/Public/JavaScript/wow.min_1712913725.js' %}"></script>
<script src="{% static 'typo3conf/ext/risa_ministry/Resources/Public/JavaScript/scripts_1712913725.js' %}"></script>
<script src="{% static 'typo3conf/ext/wacon_cookie_management/Resources/Public/JavaScript/waconcookiemanagement_1712913727.js' %}"></script>



</body></html>

mod/templates/view_applications.html
{% load static %}

<!DOCTYPE html><html lang="en-US"><head>

<meta charset="utf-8">
<!-- 
	This website is powered by TYPO3 - inspiring people to share!
	TYPO3 is a free open source Content Management Framework initially created by Kasper Skaarhoj and licensed under GNU/GPL.
	TYPO3 is copyright 1998-2024 of Kasper Skaarhoj. Extensions are copyright of their respective owners.
	Information and contribution at https://typo3.org/
-->


<link rel="shortcut icon" href="typo3conf/ext/risa_base/Resources/Public/Images/Coat.png" type="image/png">
<title>MOD: Home</title>
<meta name="generator" content="TYPO3 CMS">
<meta name="twitter:card" content="summary">

<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/bootstrap.min_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/index_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/animate_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/sweetalert_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Fonts/style_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/ministry_ui_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3temp/assets/css/a2b50b40b2_1685369889.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/ns_twitter/Resources/Public/Css/style_1712913723.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/ns_twitter/Resources/Public/Css/font-awesome/css/font-awesome.min_1712913723.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/wacon_cookie_management/Resources/Public/Css/waconcookiemanagement_1712913727.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/material_icon_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/all_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/owl.carousel.min_1712913725.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'typo3conf/ext/risa_ministry/Resources/Public/Css/owl.theme.default.min_1712913725.css' %}" media="all">



<script src="{% static 'typo3conf/ext/wacon_cookie_management/Resources/Public/JavaScript/jquery.min_1712913727.js' %}"></script>
<script src="{% static 'typo3conf/ext/risa_gov/Resources/Public/Javascript/smoothscroll_1712913725.js' %}"></script>


<meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, shrink-to-fit=no">    <script>
        (function (w, d, s, l, i) {
        w[l] = w[l] || []; w[l].push({
        'gtm.start':
            new Date().getTime(), event: 'gtm.js'
        }); var f = d.getElementsByTagName(s)[0],
        j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
            'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-NLR2CLH');
    </script>
<link rel="canonical" href="https://www.mod.gov.rw/">

<!-- This site is optimized with the Yoast SEO for TYPO3 plugin - https://yoast.com/typo3-extensions-seo/ -->
<script type="application/ld+json">[{"@context":"https://www.schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"item":{"@id":"https://www.mod.gov.rw/1","name":"MOD"}},{"@type":"ListItem","position":2,"item":{"@id":"https://www.mod.gov.rw/","name":"Home"}}]}]</script>

<style>
    input, textarea, select {
        border: 1px solid rgb(78, 78, 78) !important;
        border-radius: 4px;
        padding: 3px 5px;
        margin-bottom: 10px;
    }
</style>

</head>
<body>

<noscript>
  <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NLR2CLH" height="0" width="0"
    style="display:none;visibility:hidden">
  </iframe>
</noscript>

        <nav class="navbar sticky-top navbar-expand-lg navbar-light ministry_navbar" id="theNav">

<div class="container-fluid ministry_container">
  <a href="/" title="MOD" class="navbar-brand">
    <img src="{% static 'images/logo.png' %}" alt="Image" height="48">
</a>
<a href="/" title="MOD" class="navbar-brand logotext">
	<p class="txt_subtitle fnt_black  mabo0">MOD</p>
</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span id="navbar-hamburger" class="navbar-toggler-icon"></span>
    <span id="navbar-close" class="hidden"><i class="material-icons txt_content">close</i></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
      
        
            <li class="nav-item">
              <a class="nav-link main_option active" href="/" title="Home">
                Home
              </a>
            </li>
          
      
        
            <li class="nav-item">
              <a class="nav-link main_option " href="#" title="The Ministry">
                The Ministry
              </a>
            </li>
          
      
        
            <li class="nav-item">
              <a class="nav-link main_option " href="#" title="RDF">
                RDF
              </a>
            </li>
          
      
        
            <li class="nav-item">
              <a class="nav-link main_option " href="#" title="Activities">
                Activities
              </a>
            </li>
          
      
        
            <li class="nav-item">
              <a class="nav-link main_option " href="#" title="Updates">
                Updates
              </a>
            </li>
          
      
        
            <li class="nav-item">
              <a class="nav-link main_option " href="#" title="Publications">
                Publications
              </a>
            </li>


            <li class="nav-item">
              <a class="nav-link main_option " href="/form" title="Publications">
                Form
              </a>
            </li>
          
      
    </ul>

    
  </div>
</div>
</nav>


  <!-- SECTION LANDING STARTS -->
  <div class="container-fluid d-flex" id="section_landing">

    <div class="container align-self-center pad0">
        <h3>Application Submitted Successfully</h3>
        <h5 style="margin-top: 20px;">Details of the Application</h4>
        <ul>
            <li>Full Name: {{ application.fullname }}</li>
            <li>Social Security Number: {{ application.ssn }}</li>
            <li>Email Address: {{ application.email }}</li>
            <li>Phone Number: {{ application.phone }}</li>
            <li>Highest Level of Education Completed: {{ application.get_education_display }}</li>
            <li>Reasons for Enlisting: {{ application.reasons }}</li>
            <li>Prior Military Service: {{ application.history }}</li>
        </ul>
        <a href="/form">Submit another application</a>

        </div>
    </div>
<button onclick="topFunction()" id="backToTop" title="Go to top">↑<br><span class="txt_info txt_grey">Back top</span></button>

<!--SECTION FOOTER ENDS-->
<script src="{% static 'www.recaptcha.net/recaptcha/api_hl%3D.js' %}"></script>
<script src="{% static 'typo3conf/ext/risa_ministry/Resources/Public/JavaScript/jquery-3.6.0_1712913725.js' %}"></script>
<script src="{% static 'cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js' %}"></script>
<script src="{% static 'typo3conf/ext/risa_ministry/Resources/Public/JavaScript/popper.min_1712913725.js' %}"></script>
<script src="{% static 'typo3conf/ext/risa_ministry/Resources/Public/JavaScript/bootstrap.min_1712913725.js' %}"></script>
<script src="{% static 'typo3conf/ext/risa_ministry/Resources/Public/JavaScript/sweetalert.min_1712913725.js' %}"></script>
<script src="{% static 'typo3conf/ext/risa_ministry/Resources/Public/JavaScript/owl.carousel.min_1712913725.js' %}"></script>
<script src="{% static 'typo3conf/ext/risa_ministry/Resources/Public/JavaScript/wow.min_1712913725.js' %}"></script>
<script src="{% static 'typo3conf/ext/risa_ministry/Resources/Public/JavaScript/scripts_1712913725.js' %}"></script>
<script src="{% static 'typo3conf/ext/wacon_cookie_management/Resources/Public/JavaScript/waconcookiemanagement_1712913727.js' %}"></script>



</body></html>